set -e
true
true
/home/gabrielsanchezgarcia/miniconda3/envs/spades/bin/spades-hammer /home/gabrielsanchezgarcia/Gabriel/Terminal/Ensamblajes/0720_illumina_SENASICA/corrected/configs/config.info
/home/gabrielsanchezgarcia/miniconda3/envs/spades/bin/python3 /home/gabrielsanchezgarcia/miniconda3/envs/spades/share/spades/spades_pipeline/scripts/compress_all.py --input_file /home/gabrielsanchezgarcia/Gabriel/Terminal/Ensamblajes/0720_illumina_SENASICA/corrected/corrected.yaml --ext_python_modules_home /home/gabrielsanchezgarcia/miniconda3/envs/spades/share/spades --max_threads 16 --output_dir /home/gabrielsanchezgarcia/Gabriel/Terminal/Ensamblajes/0720_illumina_SENASICA/corrected --gzip_output
true
true
/home/gabrielsanchezgarcia/miniconda3/envs/spades/bin/spades-core /home/gabrielsanchezgarcia/Gabriel/Terminal/Ensamblajes/0720_illumina_SENASICA/K21/configs/config.info
/home/gabrielsanchezgarcia/miniconda3/envs/spades/bin/spades-core /home/gabrielsanchezgarcia/Gabriel/Terminal/Ensamblajes/0720_illumina_SENASICA/K33/configs/config.info
/home/gabrielsanchezgarcia/miniconda3/envs/spades/bin/spades-core /home/gabrielsanchezgarcia/Gabriel/Terminal/Ensamblajes/0720_illumina_SENASICA/K55/configs/config.info
/home/gabrielsanchezgarcia/miniconda3/envs/spades/bin/spades-core /home/gabrielsanchezgarcia/Gabriel/Terminal/Ensamblajes/0720_illumina_SENASICA/K77/configs/config.info
/home/gabrielsanchezgarcia/miniconda3/envs/spades/bin/spades-core /home/gabrielsanchezgarcia/Gabriel/Terminal/Ensamblajes/0720_illumina_SENASICA/K99/configs/config.info
/home/gabrielsanchezgarcia/miniconda3/envs/spades/bin/spades-core /home/gabrielsanchezgarcia/Gabriel/Terminal/Ensamblajes/0720_illumina_SENASICA/K127/configs/config.info
/home/gabrielsanchezgarcia/miniconda3/envs/spades/bin/python3 /home/gabrielsanchezgarcia/miniconda3/envs/spades/share/spades/spades_pipeline/scripts/copy_files.py /home/gabrielsanchezgarcia/Gabriel/Terminal/Ensamblajes/0720_illumina_SENASICA/K127/before_rr.fasta /home/gabrielsanchezgarcia/Gabriel/Terminal/Ensamblajes/0720_illumina_SENASICA/before_rr.fasta /home/gabrielsanchezgarcia/Gabriel/Terminal/Ensamblajes/0720_illumina_SENASICA/K127/assembly_graph_after_simplification.gfa /home/gabrielsanchezgarcia/Gabriel/Terminal/Ensamblajes/0720_illumina_SENASICA/assembly_graph_after_simplification.gfa /home/gabrielsanchezgarcia/Gabriel/Terminal/Ensamblajes/0720_illumina_SENASICA/K127/final_contigs.fasta /home/gabrielsanchezgarcia/Gabriel/Terminal/Ensamblajes/0720_illumina_SENASICA/contigs.fasta /home/gabrielsanchezgarcia/Gabriel/Terminal/Ensamblajes/0720_illumina_SENASICA/K127/first_pe_contigs.fasta /home/gabrielsanchezgarcia/Gabriel/Terminal/Ensamblajes/0720_illumina_SENASICA/first_pe_contigs.fasta /home/gabrielsanchezgarcia/Gabriel/Terminal/Ensamblajes/0720_illumina_SENASICA/K127/strain_graph.gfa /home/gabrielsanchezgarcia/Gabriel/Terminal/Ensamblajes/0720_illumina_SENASICA/strain_graph.gfa /home/gabrielsanchezgarcia/Gabriel/Terminal/Ensamblajes/0720_illumina_SENASICA/K127/scaffolds.fasta /home/gabrielsanchezgarcia/Gabriel/Terminal/Ensamblajes/0720_illumina_SENASICA/scaffolds.fasta /home/gabrielsanchezgarcia/Gabriel/Terminal/Ensamblajes/0720_illumina_SENASICA/K127/scaffolds.paths /home/gabrielsanchezgarcia/Gabriel/Terminal/Ensamblajes/0720_illumina_SENASICA/scaffolds.paths /home/gabrielsanchezgarcia/Gabriel/Terminal/Ensamblajes/0720_illumina_SENASICA/K127/assembly_graph_with_scaffolds.gfa /home/gabrielsanchezgarcia/Gabriel/Terminal/Ensamblajes/0720_illumina_SENASICA/assembly_graph_with_scaffolds.gfa /home/gabrielsanchezgarcia/Gabriel/Terminal/Ensamblajes/0720_illumina_SENASICA/K127/assembly_graph.fastg /home/gabrielsanchezgarcia/Gabriel/Terminal/Ensamblajes/0720_illumina_SENASICA/assembly_graph.fastg /home/gabrielsanchezgarcia/Gabriel/Terminal/Ensamblajes/0720_illumina_SENASICA/K127/final_contigs.paths /home/gabrielsanchezgarcia/Gabriel/Terminal/Ensamblajes/0720_illumina_SENASICA/contigs.paths
true
/home/gabrielsanchezgarcia/miniconda3/envs/spades/bin/python3 /home/gabrielsanchezgarcia/miniconda3/envs/spades/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /home/gabrielsanchezgarcia/Gabriel/Terminal/Ensamblajes/0720_illumina_SENASICA/scaffolds.fasta --misc_dir /home/gabrielsanchezgarcia/Gabriel/Terminal/Ensamblajes/0720_illumina_SENASICA/misc --threshold_for_breaking_scaffolds 3
true
